backend:
  # Use netlify identity as backend
  # name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  name: gitlab
  repo: ido.g/idog-blog-tisot
  # site_domain: cms.netlify.com
  # api_root: https://gitlab.com/ido.g/portfolio-design/api/v4
  # base_url: https://gitlab.com/ido.g/portfolio-design/
  # auth_endpoint: oauth/authorize
  # cms_label_prefix:
  auth_type: pkce
  app_id: d2015d598c23d422e2c9c1e20a0ed07fd9e1c5c4ef796a4734e522bce34ad681
  # locale: 'he'

media_folder: "/src/assets/img/"
public_folder: "/assets/img"
# publish_mode: editorial_workflow
site_url: https://ido.g.gitlab.io/idog-blog-tisot/
display_url: https://ido.g.gitlab.io/idog-blog-tisot/
logo_url: https://ido.g.gitlab.io/idog-blog-tisot/assets/favicon/android-chrome-512x512.png

# Please run "npx netlify-cms-proxy-server" for local backend
# local_backend: true
# publish_mode: editorial_workflow

collections:
  - label: "Post"
    name: "post"
    folder: "/src/posts"
    extension: "md"
    format: "frontmatter"
    media_folder: "/src/assets/img/posts/"
    public_folder: "/assets/img/posts/"
    create: true
    slug: "{{slug}}"
    preview_path: "/posts/{{slug}}"        
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string", required: true }
      - { label: "Subtitle", name: "subtitle", widget: "string", required: false }
      - { label: "Post Slug", name: "slug_title", widget: "string", required: true }
      - { label: "Published by", name: "published_by", widget: "string" }
      - { label: "Publish Date", name: "publish_date", widget: "datetime" }
      - { label: "Trip Date", name: "trip_date", widget: "datetime", required: false }
      - { label: "Trip Type", name: "trip_type", widget: "string", required: false }
      - { label: "Trip Length", name: "trip_length", widget: "number", required: false }
      - { label: "Main Image", name: "head_image", widget: "image", required: false }
      - { label: "Show main Image caption", name: "head_image_show_caption", widget: "boolean", default: false, required: false}
      - { label: "Main image caption text", name: "head_image_caption_text", widget: "string", default: "", required: false}      
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image", required: true }
      - { label: "Show thumbnail caption", name: "thumbnail_show_caption", widget: "boolean", default: false, , required: false}
      - { label: "Thumbnail caption text", name: "thumbnail_caption_text", widget: "string", default: "", required: false}
      - { label: "Tags", name: "tags", widget: "list", default: [], allow_add: true, field: {label: Tag, name: tag, widget: string} }
      - { label: "Keywords", name: "keywords", widget: "list", default: [], allow_add: true, field: {label: Keyword, name: keyword, widget: string} }
      - { label: "In Draft Mode", name: "isDraft", widget: "boolean", default: true }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Home Page"
    name: "home_page"
    folder: "/src/pages"
    create: false
    # slug: "{{slug}}"
    # preview_path: "{{slug}}"
    fields:
      - { label: "Main Image", name: "main_image", widget: "image" }
      - { label: "Main Heading", name: "main_heading", widget: "string" }
      - { label: "Secondary Heading", name: "secondary_heading", widget: "string", required: false }      
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - label: "About Page"
    name: "about_page"
    folder: "/src/pages/about"
    create: false
    # slug: "{{slug}}"
    # preview_path: "{{slug}}"
    fields:        
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Avatar", name: "avatar", widget: "image", required: false }
      - { label: "Writer's name", name: "about_name", widget: "string", required: false }
      - { label: "Writer's email", name: "email", widget: "string", required: false }
      - { label: "Writer's phone", name: "phone", widget: "string", required: false }
      - { label: "Show avatar caption", name: "avatar_show_caption", widget: "boolean", default: true }
      - { label: "Avatar caption text", name: "avatar_caption_text", widget: "string", default: "" }
      - { label: "Body", name: "body", widget: "markdown", required: false }
  - label: "Contact Page"
    name: "contact_page"
    folder: "/src/pages/contact"
    create: false
    fields:        
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown", required: false }      