backend:
  # Use netlify identity as backend
  # name: git-gateway
  branch: main
  ### enable below lines for github integration ###
  name: gitlab
  repo: ido.g/idog-blog-tisot
  # site_domain: cms.netlify.com
  # api_root: https://gitlab.com/ido.g/portfolio-design/api/v4
  # base_url: https://gitlab.com/ido.g/portfolio-design/
  # auth_endpoint: oauth/authorize
  # cms_label_prefix:
  auth_type: pkce
  app_id: d2015d598c23d422e2c9c1e20a0ed07fd9e1c5c4ef796a4734e522bce34ad681
  # locale: 'he'

media_folder: "/src/assets/img/"
public_folder: "/assets/img"
# publish_mode: editorial_workflow
site_url: https://ido.g.gitlab.io/idog-blog-tisot/
display_url: https://ido.g.gitlab.io/idog-blog-tisot/
logo_url: https://ido.g.gitlab.io/idog-blog-tisot/assets/favicon/android-chrome-512x512.png

# Please run "npx netlify-cms-proxy-server" for local backend
# local_backend: true
# publish_mode: editorial_workflow

collections:
  - label: "Post"
    name: "post"
    folder: "/src/posts"
    extension: "md"
    format: "frontmatter"
    media_folder: "/src/assets/img/posts/"
    public_folder: "/assets/img/posts/"
    create: true
    slug: "{{slug}}"
    preview_path: "/posts/{{slug}}"        
    editor:
      preview: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Published by", name: "published_by", widget: "string" }
      - { label: "Publish Date", name: "publish_date", widget: "datetime" }
      - { label: "Trip Date", name: "trip_date", widget: "datetime" }
      - { label: "Trip Type", name: "trip_type", widget: "string" }
      - { label: "Main Image", name: "head_image", widget: "image" }
      - { label: "Thumbnail Image", name: "thumbnail", widget: "image" }
      - { label: "Tags", name: "tags", widget: "list", default: [], allow_add: true, field: {label: Tag, name: tag, widget: string} }
      - { label: "Body", name: "body", widget: "markdown" }
  - label: "Page"
    name: "pages"
    folder: "/src/pages"
    create: false
    slug: "{{slug}}"
    preview_path: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }